### ISSUE TITLE
your code is not working

### ISSUE THREAD

**Issue by nitya65** [jonathanchrisp/selenium-cucumber-ruby-kickstarter#1]
Hi,
I tried to run your code, but it does not work, where are defined these two 

verify_page and enter_search(search_term)  ?
Thanks,

**Comment by jwarykowski** [comment]
Hey @nitya65, I haven't touched this code in a long time but I can quickly check to see what is going on.

**Comment by jwarykowski** [comment]
Hey @nitya65, I've pulled down the repo and it all ran as expected. I've updated the gems and changed the README.md with some small changes in PR #2. If you can give me some more details that would be appreciated.

You can find the `verify_page` method defined in both the google_home_page and google_results_page files. The `enter_search` method is only defined in the `google_home_page` file as this is the only place where you can enter a search term. You can see this [here](https://github.com/jonathanchrisp/selenium-cucumber-ruby-kickstarter/blob/master/lib/google_home_page.rb).

**Comment by jwarykowski** [comment]
Closing ticket following latest updates.
